# Generated by Django 5.1.5 on 2025-01-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="etudiant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matricul", models.BigIntegerField()),
                ("password", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
