# Generated by Django 5.1.5 on 2025-01-31 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("module", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="etudiant",
            name="matricul",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="etudiant",
            name="password",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="prof",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profition", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prof",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
