# Generated by Django 5.1.6 on 2025-02-06 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_exam_alter_etudiant_matricul_alter_etudiant_password_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="presence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_present", models.BooleanField()),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etudiant",
                        to="api.etudiant",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam",
                        to="api.exam",
                    ),
                ),
            ],
        ),
    ]
