# Generated by Django 5.1.6 on 2025-02-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_presence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="presence",
            name="is_present",
            field=models.BooleanField(default=False),
        ),
    ]
