# Generated by Django 5.1.6 on 2025-02-06 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_presence_is_present"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="time",
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
    ]
