# Generated by Django 5.1.6 on 2025-02-06 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_exam_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="presence",
            name="etudiant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="etudiant",
                to="api.etudiant",
            ),
        ),
        migrations.AlterField(
            model_name="presence",
            name="exam",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam",
                to="api.exam",
            ),
        ),
    ]
