# Generated by Django 5.1.6 on 2025-03-18 20:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="surveillance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_present", models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name="QRCodeData",
        ),
        migrations.RemoveField(
            model_name="student",
            name="name",
        ),
        migrations.AddField(
            model_name="exam",
            name="amphi",
            field=models.CharField(default="ben ba3toch", max_length=15),
        ),
        migrations.AddField(
            model_name="exam",
            name="time",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="student",
            name="level",
            field=models.CharField(
                choices=[
                    ("l1", "L1"),
                    ("l2", "L2"),
                    ("l3", "L3"),
                    ("m1", "M1"),
                    ("m2", "M2"),
                ],
                default="l1",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="matricul",
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="student",
            name="speciality",
            field=models.CharField(
                choices=[
                    ("info", "info"),
                    ("physic", "physic"),
                    ("gestion", "gestion"),
                    ("biology", "biology"),
                    ("pharmacy", "pharmacy"),
                    ("medcine", "medcine"),
                ],
                default="info",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="semester",
            field=models.CharField(
                choices=[("s1", "S1"), ("s2", "S2")], default="s1", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="speciality",
            field=models.CharField(
                choices=[
                    ("info", "info"),
                    ("physic", "physic"),
                    ("gestion", "gestion"),
                    ("biology", "biology"),
                    ("pharmacy", "pharmacy"),
                    ("medcine", "medcine"),
                ],
                default="info",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="teach",
            name="teaching",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="exam",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="surveillance",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="exams.exam"
            ),
        ),
        migrations.AddField(
            model_name="surveillance",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="exams.teacher"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="Name",
            field=models.OneToOneField(
                default=django.utils.timezone.now,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
