# Generated by Django 5.1.6 on 2025-03-31 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0002_surveillance_delete_qrcodedata_remove_student_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="is_present",
        ),
        migrations.RemoveField(
            model_name="surveillance",
            name="is_present",
        ),
        migrations.RemoveField(
            model_name="teach",
            name="teaching",
        ),
    ]
