# Generated by Django 5.1.6 on 2025-05-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0003_remove_attendance_is_present_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="secret_number",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
